TRUNCATE TABLE app.psn_earned_trophy CASCADE;
TRUNCATE TABLE app.psn_edition CASCADE;
TRUNCATE TABLE app.psn_edition_trophy_suite CASCADE;
TRUNCATE TABLE app.psn_game CASCADE;
TRUNCATE TABLE app.psn_game_image CASCADE;
TRUNCATE TABLE app.psn_played_edition CASCADE;
TRUNCATE TABLE app.psn_played_game CASCADE;
TRUNCATE TABLE app.psn_played_trophy_suite CASCADE;
TRUNCATE TABLE app.psn_player CASCADE;
TRUNCATE TABLE app.psn_trophy CASCADE;
TRUNCATE TABLE app.psn_trophy_suite CASCADE;
TRUNCATE TABLE app.psn_trophy_suite_group CASCADE;

TRUNCATE TABLE app.igdb_game CASCADE;
TRUNCATE TABLE app.igdb_candidate CASCADE;
TRUNCATE TABLE app.igdb_collection CASCADE;
TRUNCATE TABLE app.igdb_company CASCADE;
TRUNCATE TABLE app.igdb_game_collection CASCADE;
TRUNCATE TABLE app.igdb_game_company CASCADE;