TRUNCATE TABLE app.player CASCADE;
TRUNCATE TABLE app.game CASCADE;
TRUNCATE TABLE app.trophy CASCADE;
TRUNCATE TABLE app.played_game CASCADE;
TRUNCATE TABLE app.earned_trophy CASCADE;

TRUNCATE TABLE app.igdb_game CASCADE;
TRUNCATE TABLE app.igdb_candidate CASCADE;
TRUNCATE TABLE app.igdb_collection CASCADE;
TRUNCATE TABLE app.igdb_company CASCADE;
TRUNCATE TABLE app.igdb_mapping CASCADE;